import axios from "axios";

const BACKEND_URL = 'https://react-native-course-eed25-default-rtdb.firebaseio.com';

export async function storeExpense(expenseData) {
    const response = await axios.post(
        BACKEND_URL + '/expenses.json', expenseData
    );
    return response.data.name; // id generated by FireBase
}

export async function fetchExpenses() {
    const response = await axios.get(BACKEND_URL + '/expenses.json');
    
    const expenses = [];

    for (const key in response.data) {
        const obj = response.data[key];
        
        const expenseObj = {
            id: key,
            amount: obj.amount,
            date: new Date(obj.date),
            description: obj.description,
        };

        expenses.push(expenseObj);
    }

    return expenses;
}

export function updateExpense(id, expenseData) {
    return axios.put(BACKEND_URL + `/expenses/${id}.json`);
}

export function deleteExpense(id) {
    return axios.delete(BACKEND_URL + `/expenses/${id}.json`);
}